---
apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: demo
spec:
  containers:
  - name: rsync-container
    image: ubuntu:latest
    command: ["/bin/sh", "-c"]
    args:
    - rsync -av /source-directory/ /destination-directory/
    volumeMounts:
    - name: shared-data
      mountPath: /source-directory
  - name: web-server-container
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  volumes:
  - name: shared-data
    emptyDir: {}
