---
apiVersion: v1
kind: Pod
metadata:
  name: app-secret-container
spec:
  containers:
  - name: mycontainer
    image: ubuntu:latest
    command: ["/bin/sh", "-c"]
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret1
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret1
            key: password
  restartPolicy: Never
